### ISSUE TITLE
Foreign accounts - správcovský účet

### ISSUE THREAD

**Issue by alesmraz** [seznam/sklik-data-studio-connector#1]
Dobrý den,

Je možné nástroj použít pro tzv. **Správcovský účet**? Tzn. že pod jedním napojením bych viděl všechny podřízené účty a mohl generovat statiky z nich? 

V napojení je nastavení _UserId_ pouze pro jeden účet. Potřeboval bych aby se připojili všechny účty ( mám jich podřízeno 100+ takže není možné každý napojit zvlášť)

Díky.

**Comment by ChocoTUx** [comment]
Dobrý den, 

bohužel nic takové neumí. Teorieticky je konektor možný na to upravit, ale to aktuálně není naším cílem, chceme se zaměřit na mainstream a tedy rozšiřovat možnosti v rámci jednoho účtu. 

Stejskal

**Comment by alesmraz** [comment]
Dobře, díky moc za informaci. Pokud někdy konektor upravím pro tyto účely, určitě dám Pull request.
