### ISSUE TITLE
Nejde povolit konektor

### ISSUE THREAD

**Issue by mates135** [seznam/sklik-data-studio-connector#10]
Dobrý den, neustále mi to hází tuto chybu, když chci konektor povolit https://prnt.sc/10n88ic 

Ví někdo co s tím? Používám tento konektor AKfycby9gWxFBQ84_yIDPWuJg7JEfY7GWWkpDA-S5fZWao1QybkAjggsAtHzSZl14yEIhZRq

**Comment by ChocoTUx** [comment]
Dobrý den, 

tam bych čekal nějaké nastavení ochrany. Konektor přistupuje do Drive, kde vytváří logovací soubor (pro případný debug) a dle všeho to Google pro váš účet zablokoval. 
Nicméně používáte starou verzi. Už máme v3 - AKfycbz5dp60Pq7R-gV3j2fIGoviSCojh0A7I3V3jT49BEMWzm6Cdzd0kPDiy7HVUvXhFLUINA

**Comment by mates135** [comment]
Perfektní, ta v3 funguje. 

Dával jsem tam původně to, co je v návodu https://prnt.sc/10na20o

Díky
