### ISSUE TITLE
Nefunkční connector

### ISSUE THREAD

**Issue by RespectOP** [seznam/sklik-data-studio-connector#15]
Zdravím,

nefunguje connector, kompletně vypadl a nejde ho ani najít dle ID. 
Můžete zaslat nové ID, protože v protokolu je ve verzi 4.0.0, i když došlo k aktualizaci.

**Comment by ChocoTUx** [comment]
Bohužel to není tím.

Google nás tlačil do úpravy práv kolem přistupování na Drive a dřív než jsem se s ním stihl domluvit co a jak, tak mi tu aplikaci zavřel :(. Tak jsem upravil věci a snad mi to co nejdříve schválí a pustí.

**Comment by RespectOP** [comment]
Ok, takže teď jen vyčkat nebo budeme muset něco potom měnit, jakmile to schválí?

Díky

**Comment by ChocoTUx** [comment]
No, tak se asi ukazuje, že to možná bude něco jiného. Minulý týden jsme migrovali něco na Seznamáckém Google disku a nejspíše se to úplně nepovedlo jak mělo :(.

**Comment by RespectOP** [comment]
Jasný, aspoň víte, že chyba je někde jinde a může se to rychleji opravit ;)

**Comment by ChocoTUx** [comment]
Zkuste. Mělo by to být opravené (alespoň následky z migrace).

**Comment by RespectOP** [comment]
Vypadá to, že již ok.  Díky
