### ISSUE TITLE
Chybí rozpočet

### ISSUE THREAD

**Issue by MorenXXL** [seznam/sklik-data-studio-connector#2]
Nedaří se mi najít v konektoru položku Rozpočet. Je součástí API? Nebo se jen špatně dívám? Prošel jsem to několikrát a mám pocit, že tam prostě nikde není možnost zobrazení denního rozpočtu kampaně.

**Comment by ChocoTUx** [comment]
Dobrý den, 
denní rozpočet skutečně GDS neumí zobrazovat. 
Jde přes API získat, ale pomocí jiných metod, než které používáme pro stahování dat do GDS
