### ISSUE TITLE
UserID

### ISSUE THREAD

**Issue by davidpajer** [seznam/sklik-data-studio-connector#4]
Jak lze zjistit User ID v Skliku? Utilitka na uvedeném URL není - https://bit.ly/2uMuKgL

**Comment by ChocoTUx** [comment]
Dobrý den, 
aktuálně odzkoušeno a link stále funguje.

**Comment by PitrsxD** [comment]
Utilitka na UserID nedostupná - "Je nám líto, ale soubor momentálně nelze otevřít."
