### ISSUE TITLE
PNO, duplicitní "Kampaň: Prokliky"

### ISSUE THREAD

**Issue by Ren315** [seznam/sklik-data-studio-connector#5]
Zdravím, mám tři postřehy: 
- Nesedí hodnota PNO "Kampaň: PNO" 
- nepasuje ani klasický výpočet (Kampaň: (Kč) Cena/Kampaň: Hodnota konverze) * 100.
- "Kampaň: Prokliky" je duplicitní (z toho první hodnota obsahuje nesmyslná čísla)
Snad nedělám někde chybu. Díky za pomoc

**Comment by ChocoTUx** [comment]
Dobrý den, 

děkujeme za postřehy. Nicméně hodnoty PNO spíše nasvědčují na nějaký problém přímo kolem samotného API nebo celého Skliku. Můžete prosím s podrobným popisem (na jakém účtu, jaké hodnoty získáváte a jaké by jste očekávali) kontaktovat podporu Skliku - https://napoveda.sklik.cz/casto-kladene-dotazy/kontaktni-formular/
Na duplicitu metriky se podíváme a upravíme v nejbližším balíku oprav až sesbíráme zpětnou vazbu od dalších uživatelů.
