### ISSUE TITLE
Desatinná čiarka - čísla sú vysoke

### ISSUE THREAD

**Issue by dbsk1** [seznam/sklik-data-studio-connector#7]
Zdravím,

pri importe sa mi čísla zjavne berú bez čiarky a teda na miesto 
10 548,84 Kč
mám 1 054 884 Kč

Nenapadá vás čím to môže byť?

Moc pekne Ďakujem

**Comment by ChocoTUx** [comment]
Dobrý den, 

Mělo by se to dít pouze u metrik v rámci "Účet: *" a jde o to, že API vrací celá čísla v haléřích. Přepočet na klasický formát Kč s desetinou čárkou se musí dělat v rámci konektoru a při rozšiřování verze 2.0 se na to zapomnělo. Už se chystá update, tento týden, popřípadě příští to bude nasazené (sledujte tady na githubu readme a jeho changelog a bude to tam zmíněné).

**Comment by dbsk1** [comment]
Super, ďakujem za rýchlu odpoveď

👍👍
